INSERT INTO tbl_category (id, name, description, required_composer) VALUES
	(2, '19th/20th/21st Century Sonata', NULL, NULL),
	(3, '20th/21st Century Composers', 'Music of the 20th/21st century', NULL),
	(4, '20th/21st Century English Art Song', 'Any selection from works of such composers as Barber, Copland, Head, Quilter, Rorem, etc. The selection must be sung in English.', NULL),
	(5, '20th/21st Century Sonata', NULL, NULL),
	(7, 'Baroque Composers', 'Music of the Baroque Period.  1580 - 1750', NULL),
	(8, 'Baroque or Classical Composers', 'Music of the Baroque or Classical Period.', NULL),
	(9, 'Baroque - J.S. Bach', NULL, 'J.S. Bach'),
	(10, 'Baroque - J.S. Bach - Unaccompanied', NULL, 'J.S. Bach'),
	(11, 'Baroque, Classical, or Romantic Sonata', NULL, NULL),
	(12, 'Baroque or Classical Sonata', NULL, NULL),
	(13, 'Baroque Sonata', NULL, NULL),
	(14, 'Baroque Unaccompanied', NULL, NULL),
	(15, 'Canadian Composers', 'For extensive listings of music by Canadian composers, refer to the Contemporary Showcase Syllabus www.acnmp.ca or the Canadian Music Centre www.musiccentre.ca.', NULL),
	(16, 'Celtic/Folk Music', NULL, NULL),
	(17, 'Classical Composers', 'Music of the Classical Period. Where there are two classes for Classical era compositions, one class is for sonata/sonatina movements only (including divertimentos), and the other is for all other compositions from the Classical era (e.g. bagatelles, theme & variations).', NULL),
	(18, 'Classical Sonata', NULL, NULL),
	(19, 'Concert Étude', NULL, NULL),
	(20, 'Concerto', 'Concerto classes are understood to include concerto, concertino and multi-movement concerted works.  Movements from these works must be entered in Concerto classes.', NULL),
	(21, 'Early Romantic Composers', 'Music of the Early Romantic Period.', NULL),
	(22, 'Folk Song', 'Songs in any language, with the composer unknown, that have endured and been passed down by oral tradition often with considerable variation OR songs by known composers (for example J.J. Niles, Ralph Vaughan Williams, etc.), in which the form and the sentiment are as in the traditional folk songs.', NULL),
	(23, 'French Composers', NULL, NULL),
	(24, 'French Mélodie', 'Any selection from the works of such composers as Berlioz, Bizet, Chabrier, Chausson, Debussy, Duparc, Fauré, Hahn, Milhaud, Poulenc, Ravel, etc. The selection must be sung in French.', NULL),
	(25, 'German Lieder', '19th and 20th Century German music in which the voice and piano share equally in enhancing and illustrating the meaning of the poetry.  Any selection from the works of such composers as Berg, Brahms, Liszt, Mahler, Schöenberg, Schubert, Schumann, R. Strauss, Wolf, etc.  The selection must be sung in German.', NULL),
	(26, 'Gilbert & Sullivan', 'A selection taken from a Gilbert & Sullivan Operettas. Participants may include the spoken passages leading up to it and may use hand props, costumes, and movement. Not a medley of songs. No chorus.', 'Gilbert & Sullivan'),
	(27, 'Italian Art Song', 'Any selection from the works of such composers as Bellini, Caccini, Caldara, Carissimi, Donaudy, Giordani, Lotti, Pergolesi, Scarlatti, Torelli, Vivaldi, etc. These selections are not to be confused with Italian ‘Canzone’ - which refers to Italian songs in general and not specifically to the art song genre. The selection must be sung in Italian.', NULL),
	(28, 'J.S. Bach Aria', NULL, 'J.S. Bach'),
	(29, 'Late Romantic Composers', 'Music of the Late Romantic Period. A selection from the works of such composers as Albéniz, Glière, Granados, Janáček, MacDowell, Medtner, Moszkowski, Rachmaninoff, Scriabin, etc.', NULL),
	(30, 'Lute Song (1500 - 1700)', NULL, NULL),
	(31, 'Manitoba Composers', NULL, NULL),
	(32, 'Multi-Movement Work', NULL, NULL),
	(33, 'Musical Theatre', 'A selection taken from a stage show/production (not a TV/Movie production/musical). Participants may include the spoken passages leading up to it and may use hand props, costumes, and movement. Not a medley of songs. No chorus.', NULL),
	(34, 'Opera', NULL, NULL),
	(35, 'Opera Aria', NULL, NULL),
	(36, 'Oratorio Aria', 'Any selection from a recognized sacred oratorio such as Creation, Elijah, Messiah, St. Matthew Passion, St. Paul, Samson, etc.', NULL),
	(37, 'Own Choice', NULL, NULL),
	(38, 'Recital Group', 'Two or three selections by one or more composers. Participants will be adjudicated on the selection of the group; i.e. technique,  style, appropriateness and interpretation. The purpose of these classes is to provide an opportunity for students to prepare and perform a recital program in public. Participants will receive adjudication only. Time limits must be observed.', NULL),
	(39, 'Renaissance Composers', 'Music of the Renaissance Period.', NULL),
	(40, 'Romantic Composers', 'Music of the Romantic Period. The music of Sergei Rachmaninoff is regarded as music of this era.', NULL),
	(41, 'Romantic Composers or 20th/21st Century Composers', NULL, NULL),
	(42, 'Sacred', NULL, NULL),
	(43, 'Sonata', 'Sonata classes are understood to include sonata, sonatina and divertimento. Movements from these works must be entered in Sonata classes. One sonata movement may be played in the Recital Group class.', NULL),
	(44, 'Spanish Art Song', 'Any selection from the works of such composers as Bidaola, Caballero, de Falla, Giro, Granados, Obradors, etc. These selections are not to be confused with Spanish ‘Canción’ - which refers to Spanish songs in general and not specifically to the art song genre. The selection must be sung in Spanish.', NULL),
	(45, 'Study/Étude', NULL, NULL),
	(46, 'TV/Movie Musical', 'A selection taken from a TV/Movie production/musical.', NULL),
	(48, 'Madrigal', 'An unaccompanied choral composition in several parts usually dating from the 14th to 17th centuries, usually polyphonic in style, and with secular text.', NULL),
	(51, 'Concert Group', NULL, NULL),
	(52, 'Operetta/Musical Theatre Excerpts', NULL, NULL),
	(56, 'Barbershop', NULL, NULL),
	(57, 'Multilingual', NULL, NULL),
	(58, 'Action songs and singing games', NULL, NULL),
	(59, 'Songs with movement', NULL, NULL),
	(60, 'First year of instruction', NULL, NULL),
	(61, 'One or more years of instruction', NULL, NULL),
	(62, 'Second year of instruction', NULL, NULL),
	(63, 'Two or more years of instruction', NULL, NULL),
	(64, 'Own 2nd choice', NULL, NULL),
	(65, 'Canadian Musicals - Up Tempo', NULL, NULL),
	(66, 'Canadian Musicals - Ballad', NULL, NULL),
	(67, 'Musicals 1965 to 1999 - Up Tempo', NULL, NULL),
	(68, 'Musicals 1965 to 1999 - Ballad', NULL, NULL),
	(69, 'Musicals 2000 to Present - Up Tempo', NULL, NULL),
	(70, 'Musicals 2000 to Present - Ballad', NULL, NULL),
	(71, 'Musicals prior to 1965 - Up Tempo', NULL, NULL),
	(72, 'Musicals prior to 1965 - Ballad', NULL, NULL);
