INSERT INTO tbl_instruments (id, name) VALUES
	(1, 'Voice'),
	(2, 'Piano'),
	(3, 'Violin'),
	(4, 'Viola'),
	(5, 'Cello'),
	(6, 'Double Bass'),
	(7, 'Harp'),
	(8, 'Classical Guitar'),
	(9, 'Bassoon'),
	(10, 'Clarinet'),
	(11, 'English Horn'),
	(12, 'Oboe'),
	(13, 'Flute'),
	(14, 'Piccolo'),
	(15, 'Recorder'),
	(16, 'Saxophone'),
	(17, 'French Horn'),
	(18, 'Trumpet'),
	(19, 'Trombone/Euphonium'),
	(20, 'Tuba');
