INSERT INTO tbl_subdiscipline (id, "disciplineID", name, description, max_performers, min_performers, "performer_type", price) VALUES
	(1, 11, 'bassoon solo', NULL, 1, 1, 'SOLO', 30.00),
	(2, 1, 'brass chamber group', '3 or more brass instruments with or without piano.  One performer per part.  If piano is used, the pianist must be an eligible member of the group and must not be playing an accompaniment or an orchestral reduction.', NULL, 3, 'GROUP', 40.00),
	(3, 1, 'brass duet', '2 brass instruments, with or without piano accompaniment.', 2, 2, 'GROUP', 40.00),
	(4, 1, 'brass ensemble', '3 or more brass instruments, with or without piano accompaniment.  At least one part being played by two or more performers.', NULL, 3, 'GROUP', 40.00),
	(5, 1, 'brass solo', NULL, 1, 1, 'SOLO', 30.00),
	(7, 9, 'cello solo', NULL, 1, 1, 'SOLO', 30.00),
	(8, 11, 'clarinet solo', NULL, 1, 1, 'SOLO', 30.00),
	(9, 3, 'classical guitar chamber group', '3 or more classical guitars with or without piano.  One performer per part.  If piano is used, the pianist must be an eligible member of the group and must not be playing an accompaniment or an orchestral reduction.', NULL, 3, 'GROUP', 40.00),
	(10, 3, 'classical guitar duet', '2 classical guitars', 2, 2, 'GROUP', 40.00),
	(11, 3, 'classical guitar ensemble', '3 or more classical guitars, generally more than one person to a part.  With or without piano accompaniment.', 9, 3, 'GROUP', 40.00),
	(12, 3, 'classical guitar orchestra', '10 or more performers, one or more players per part.', NULL, 10, 'GROUP', 40.00),
	(13, 3, 'classical guitar solo', NULL, 1, 1, 'SOLO', 30.00),
	(15, 9, 'double bass solo', NULL, 1, 1, 'SOLO', 30.00),
	(16, 11, 'english horn solo', NULL, 1, 1, 'SOLO', 30.00),
	(17, 11, 'flute solo', NULL, 1, 1, 'SOLO', 30.00),
	(18, 1, 'french horn solo', NULL, 1, 1, 'SOLO', 30.00),
	(19, 4, 'handbell solo', NULL, 1, 1, 'SOLO', 30.00),
	(20, 9, 'harp solo', NULL, 1, 1, 'SOLO', 30.00),
	(21, 6, 'mallet solo', NULL, 1, 1, 'SOLO', 30.00),
	(22, 2, 'mixed instruments chamber group', 'Combination of 3 or more recognized orchestral instruments including harp, guitar, recorder, and/or percussion with or without piano and/or one voice.  One performer per part.  If piano is used, the pianist must be an eligible member of the group and must not be playing an accompaniment or an orchestral reduction.', NULL, 3, 'GROUP', 40.00),
	(23, 2, 'mixed instruments duet', '2 recognized orchestral instruments including harp, guitar, recorder, and/or percussion with or without piano accompaniment.  One performer per part.  If piano is used, the pianist must be an eligible member of the group and must not be playing an accompaniment or an orchestral reduction.', 2, 2, 'GROUP', 40.00),
	(24, 5, 'multi-discipline w.a. mozart', NULL, 1, 1, 'GROUP', 40.00),
	(25, 6, 'multiple percussion solo', NULL, 1, 1, 'SOLO', 30.00),
	(29, 11, 'oboe solo', NULL, 1, 1, 'SOLO', 30.00),
	(30, 7, 'one piano - six hands', NULL, 3, 3, 'GROUP', 40.00),
	(31, 6, 'percussion chamber group', '3 or more percussion instruments, with or without piano.  One performer per part.  If piano is used, the pianist must be an eligible member of the group and must not be playing an accompaniment or an orchestral reduction.', NULL, 3, 'GROUP', 40.00),
	(32, 6, 'percussion duet', '2 percussion instruments, with or without piano accompaniment.', 2, 2, 'GROUP', 40.00),
	(33, 6, 'percussion ensemble', '3 or more percussion instruments, with or without piano accompaniment.', NULL, 3, 'GROUP', 40.00),
	(34, 7, 'piano duet', NULL, 2, 2, 'GROUP', 40.00),
	(35, 7, 'two pianos - four hands', NULL, 2, 2, 'GROUP', 40.00),
	(36, 7, 'piano solo', NULL, 1, 1, 'SOLO', 30.00),
	(37, 11, 'piccolo solo', NULL, 1, 1, 'SOLO', 30.00),
	(38, 8, 'pipe organ solo', NULL, 1, 1, 'SOLO', 30.00),
	(39, 11, 'recorder consort', '3 to 10 performers.  Normally one performer per part.  Any combination of recorders.', 10, 3, 'GROUP', 40.00),
	(40, 11, 'recorder solo', NULL, 1, 1, 'SOLO', 30.00),
	(41, 11, 'saxophone solo', NULL, 1, 1, 'SOLO', 30.00),
	(42, 6, 'snare drum solo', NULL, 1, 1, 'SOLO', 30.00),
	(43, 9, 'string chamber group', '3 or more string instruments, with or without piano.  One performer per part.  If piano is used, the pianist must be an eligible member of the group and must not be playing an accompaniment or an orchestral reduction.', NULL, 3, 'GROUP', 40.00),
	(44, 9, 'string duet', '2 stringed instruments, with or without piano accompaniment.', 2, 2, 'GROUP', 40.00),
	(45, 9, 'string ensemble', '3 to 12 stringed instruments, with or without piano accompaniment.  At least one part being played by two or more performers.', 12, 3, 'GROUP', 40.00),
	(46, 9, 'string orchestra', '13 or more stringed instruments, with or without piano accompaniment.  At least one part being played by two or more performers.', NULL, 13, 'GROUP', 40.00),
	(47, 9, 'string solo', NULL, 1, 1, 'SOLO', 30.00),
	(48, 6, 'timpani solo', NULL, 1, 1, 'SOLO', 30.00),
	(50, 1, 'trombone/euphonium solo', NULL, 1, 1, 'SOLO', 30.00),
	(51, 1, 'trumpet solo', NULL, 1, 1, 'SOLO', 30.00),
	(52, 1, 'tuba solo', NULL, 1, 1, 'SOLO', 30.00),
	(53, 7, 'two pianos - eight hands', NULL, 4, 4, 'GROUP', 40.00),
	(54, 9, 'viola solo', NULL, 1, 1, 'SOLO', 30.00),
	(55, 9, 'violin solo', NULL, 1, 1, 'SOLO', 30.00),
	(56, 2, 'Family and/or Friends', 'This class is designed to promote recreational music making. Two or more singers/instrumentalists, any number of parts.', NULL, 2, 'GROUP', 40.00),
	(57, 10, 'vocal duet', NULL, 2, 2, 'GROUP', 40.00),
	(58, 14, 'vocal group', 'Musical Theatre - 5 or more performers.  From a stage production.  No chorus.', NULL, 5, 'GROUP', 40.00),
	(59, 10, 'vocal quartet', NULL, 4, 4, 'GROUP', 40.00),
	(60, 10, 'vocal solo', NULL, 1, 1, 'SOLO', 30.00),
	(61, 10, 'vocal trio', NULL, 3, 3, 'GROUP', 40.00),
	(62, 11, 'woodwind chamber group', '3 or more woodwind instruments with or without piano.  One performer per part.  If piano is used, the pianist must be an eligible member of the group and must not be playing an accompaniment or an orchestral reduction.', NULL, 3, 'GROUP', 40.00),
	(63, 11, 'woodwind duet', ' 2 woodwind instruments, with or without piano accompaniment.', 2, 2, 'GROUP', 40.00),
	(64, 11, 'woodwind ensemble', '3 or more woodwind instruments, with or without piano accompaniment.  At least one part being played by two or more performers.', NULL, 3, 'GROUP', 40.00),
	(65, 11, 'woodwind solo', NULL, 1, 1, 'SOLO', 30.00),
	(66, 12, 'vocal ensemble', '5 to 12 Singers - conducted or unconducted.', 12, 5, 'COMMUNITY', 50.00),
	(67, 12, 'choir', '13 or more singers.  This designation shall include University and Conservatory Choirs.', NULL, 13, 'COMMUNITY', 50.00),
	(68, 4, 'handbell ensemble', '2 to 4 performers.', 4, 2, 'COMMUNITY', 50.00),
	(69, 4, 'handbell choir', '5 or more performers.', NULL, 5, 'COMMUNITY', 50.00),
	(72, 12, 'female choir', '13 or more singers.', NULL, 13, 'COMMUNITY', 50.00),
	(73, 12, 'male choir', '13 or more singers.', NULL, 13, 'COMMUNITY', 50.00),
	(74, 12, 'service group', 'Groups such as: Brownies, Beavers, Boy Scouts, Girl Guides, Explorers, C.G.I.T., Pioneers Girls, C.S. Brigade, 4-H, Cadets. Fraternal Organizations, Service Clubs, etc.', NULL, 2, 'COMMUNITY', 50.00),
	(75, 12, 'community choir', '13 or more singers.  Shall include any group, the majority of who are from a specified geographical area or are connected through involvement in an organization/facility.', NULL, 13, 'COMMUNITY', 50.00),
	(76, 13, 'school chorus - mixed', '13 or more singers.  A School Chorus may be composed of one grade or a combination of grades. In Chorus Classes, it is not necessary to include students representing every grade specified in the class description. School choirs that contain grade combinations other than those specified in particular classes in the syllabus should enter the “ANY OTHER GRADE COMBINATION” class.', NULL, 13, 'SCHOOL', 50.00),
	(77, 13, 'classroom choir', 'A Classroom Choir shall consist of 90% or more of the students enrolled in a class. The total number of students shall not exceed 35. Choirs with more than 35 students should enter School Chorus classes.', 35, 2, 'SCHOOL', 50.00),
	(78, 13, 'school chorus - male - changed or changing voices', '13 or more singers.  A School Chorus may be composed of one grade or a combination of grades. In Chorus Classes, it is not necessary to include students representing every grade specified in the class description. School choirs that contain grade combinations other than those specified in particular classes in the syllabus should enter the “ANY OTHER GRADE COMBINATION” class.', NULL, 13, 'SCHOOL', 50.00),
	(79, 13, 'school chorus - female', '13 or more singers.  A School Chorus may be composed of one grade or a combination of grades. In Chorus Classes, it is not necessary to include students representing every grade specified in the class description. School choirs that contain grade combinations other than those specified in particular classes in the syllabus should enter the “ANY OTHER GRADE COMBINATION” class.', NULL, 13, 'SCHOOL', 50.00),
	(80, 13, 'school chorus - male - unchanged voices', '13 or more singers.  A School Chorus may be composed of one grade or a combination of grades. In Chorus Classes, it is not necessary to include students representing every grade specified in the class description. School choirs that contain grade combinations other than those specified in particular classes in the syllabus should enter the “ANY OTHER GRADE COMBINATION” class.', NULL, 13, 'SCHOOL', 50.00),
	(81, 13, 'school vocal ensemble', '5 - 12 singers.', 12, 5, 'SCHOOL', 50.00),
	(82, 13, 'school orff ensemble', NULL, NULL, 2, 'SCHOOL', 50.00),
	(83, 13, 'school string ensemble', '3 to 12 stringed instruments, with or without piano accompaniment.  One part by 2 or more performers.', 12, 3, 'SCHOOL', 50.00),
	(84, 13, 'school string orchestra', '13 or more stringed instruments, with or without piano accompaniment.  At least one part being played by two or more performers', NULL, 13, 'SCHOOL', 50.00),
	(85, 13, 'school guitar ensemble', '3 to 9 performers with at least one part with two or more performers.', 9, 3, 'SCHOOL', 50.00),
	(86, 13, 'school guitar orchestra', '10 or more performers with one or more players per part.', NULL, 10, 'SCHOOL', 50.00),
	(87, 13, 'school recorder consort', '3 to 8 performers. Normally one person per part.  May include any combination of recorders as well as other appropriate instruments.', 8, 3, 'SCHOOL', 50.00),
	(88, 13, 'school recorder ensemble', 'No limit on number of performers.  Any combination of recorders.', NULL, 2, 'SCHOOL', 50.00),
	(89, 13, 'school handbell ensemble', '3 to 6 performers.  Normally one person to a part.', 6, 3, 'SCHOOL', 50.00),
	(90, 13, 'school handbell choir', '7 or more performers.', NULL, 7, 'SCHOOL', 50.00),
	(93, 14, 'vocal solo - musical theatre', NULL, 1, 1, 'SOLO', 30.00),
	(94, 14, 'vocal duet - musical theatre', NULL, 1, 1, 'GROUP', 40.00),
	(95, 14, 'vocal trio - musical theatre', NULL, 1, 1, 'GROUP', 40.00),
	(96, 14, 'vocal quartet - musical theatre', NULL, 1, 1, 'GROUP', 40.00);
